### ISSUE TITLE
Any chance this will be updated to 2.4.80?

### ISSUE THREAD

**Issue by pouar** [libcg/archlinux-libdrm-amd#2]
Or has the changes been upstreamed already? I'm currently relying on the old libdrm-amdgpo in the meantime, and vulkan-amd doesn't seem to work on it. At least on the older Radeon R9 290.

**Comment by libcg** [comment]
Patches need to be rebased, I tried and it got pretty messy. Also I don't have access to my hardware right now.

**Comment by libcg** [comment]
OK, I observed it's breaking some software depending on libdrm and I have access to my graphics card. I'll see what I can do.

**Comment by libcg** [comment]
Until we get new patches from AMD I'm abandoning this. I got 17.10 drivers working using the 17.10 libdrm blob. Closing.
